/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_tony_daemontest_NativeDaemon */

#ifndef _Included_com_example_tony_daemontest_NativeDaemon
#define _Included_com_example_tony_daemontest_NativeDaemon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_tony_daemontest_NativeDaemon
 * Method:    doDaemon
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IZ)V
 */
JNIEXPORT void JNICALL Java_com_example_tony_daemontest_NativeDaemon_doDaemon
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
